language: node_js
node_js:
  - "8"
  - "12"
  - "node"
deploy:
  provider: npm
  edge: true
  email: engineering-managers@wikimedia.de
  api_key:
    secure: Wb3s5/hg164RxmtTY9AR9gWe2K43teyK5iCPY3leb/erAJyBqfhpSZPKyvyhHHt3bAQ8krOLX/1b8iwosfPjd8jGtP243oVgi/ijyn1x1qrwUggRw1cMhnIDfjxr7uEohBYzZJbHQHQkVcEVZPmG4t6eu5nPJFFg9Syc1JGllgIAXtyyRngq0rZmTGXapoyxgwDlfjYwcAAvbcPfqhdsLM6AP0ZrU2afiBZaAC4a2j+2fsmlhIVSPkFHf/3z86lQFYHLZpCmyD3jOvI1SnshDcFS8h4eW4ojoclqFsfcQKofUDEb6TxXi5ntsz5DU16ebJSDKxsBsPnWjYY2c/Q0ez832CCZc4/A4FoFlzLaXUs1PUmufl6tQJ1hn9xs0cTQLQXc4zuZCjntm5dAFFNMelUHV6YrsJOG5P/TZP83vMvvHZICSDc4mCBgH1alSFunaVY3NghpfffZ1ZKnW5RQbawvT9J0TinvlJVTL9HdBnk75JAtY/jFsfrNWMgh4jlvqT8je2Vhk+YaA3voaPpbMUSG/PBwYpbl82geKnjJVW69RVHEFIpchySaTjo9zm17182XfwHMM4UQFYiThze7cz3y/Gkuma3Kdck3tBo9CmEuCrNZKsL+A6q7Eyvxu8PbebNcJkUgANOkuvQ7OSZGRmTRzaAgLkG5O3/6P1Jeepk=
  on:
    tags: true
    branch: master
    condition: "$TRAVIS_NODE_VERSION = 12"
script:
  npm test
